name: Fetch Conjur Secret
 
on:
  push:
    branches: [ main ]
 
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq
 
    - name: Authenticate to Conjur and retrieve secret
      run: |
        set -e
        CONJUR_ACCOUNT="conjur"
        CONJUR_APPLIANCE_URL="https://pwclab.secretsmgr.cyberark.cloud"
        CONJUR_AUTHN_LOGIN="host/data/github-app"
        CONJUR_API_KEY="2srfma12z1wg0mvbd8w6mfpg4a268a8621av9f7y3nvpg6r284mv0t"
        CONJUR_VAR_KEY="data/vault/conjurtest/mysecret/password"
 
        echo "=============================="
        echo "Logging into Conjur..."
        echo "Account: $CONJUR_ACCOUNT"
        echo "Appliance URL: $CONJUR_APPLIANCE_URL"
        echo "Authn Login: $CONJUR_AUTHN_LOGIN"
        echo "=============================="
 
        echo "Authenticating..."
 
        FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
        echo "Calling authn URL: $FULL_AUTHN_URL"
 
        RESPONSE=$(curl -i -s -w "\n%{http_code}" \
          --request POST \
          --data "$CONJUR_API_KEY" \
          "$FULL_AUTHN_URL")
 
        echo "Full /authenticate response:"
        echo "$RESPONSE"
 
        BODY=$(echo "$RESPONSE" | sed '$d')
        STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
 
        if [ "$STATUS_CODE" != "200" ]; then
          echo "Authentication failed"
          echo "Status: $STATUS_CODE"
          echo "Body:"
          echo "$BODY"
          exit 1
        fi
 
        AUTHN_TOKEN=$(echo "$BODY" | base64 | tr -d '\r\n')
        echo "::add-mask::$AUTHN_TOKEN"
        echo "Authentication successful"
        echo "=============================="
 
        echo "Fetching secret..."
 
        RAW_PATH=data%2Fvault%2Fconjurtest%2Fmysecret%2Fpassword

 
        SECRET_URL=$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/$RAW_PATH
        echo "Secret fetch URL: $SECRET_URL"
 
        SECRET=$(curl -s -w "\n%{http_code}" \
          -H "Authorization: Token token=$AUTHN_TOKEN" \
          "$SECRET_URL")
 
        SECRET_VALUE=$(echo "$SECRET" | head -n1)
        SECRET_STATUS=$(echo "$SECRET" | tail -n1)
 
        echo "Secret fetch status: $SECRET_STATUS"
        if [ "$SECRET_STATUS" != "200" ]; then
          echo "Failed to fetch secret"
          echo "Response:"
          echo "$SECRET"
          exit 1
        fi
 
        echo "$SECRET_VALUE"
        echo "Retrieved secret: $SECRET_VALUE"
